notifications:
  email:
    recipients:
    - matthieu@treussart.com
    on_success: change
    on_failure: always
language: python
python:
- '3.5'
- '3.6'
os:
- linux
before_script:
- "pip install wheel"
script:
- "./test.sh"
