notifications:
  email:
    recipients:
    - matthieu@treussart.com
    on_success: change
    on_failure: always
language: python
python:
- '3.9'
os:
- linux
before_script:
- "pip install pipenv"
- "pipenv install --deploy --dev"
script:
- "pipenv run test"
